#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Cloudflare migration wizard — the ACCOUNT-SIDE half of moving the site to
# Cloudflare Pages. The repo-side half (deploy-cloudflare.yml, which assembles
# the allowlisted _site and direct-uploads it) is already written; this walks
# the owner through the parts only a human with the accounts can do.
#
# DELIBERATE: no value is ever typed into this script. `gh` is not installed
# on this box, and both values the deploy needs (account id, API token) travel
# Cloudflare tab → GitHub tab directly. Nothing lands in a .env, nothing
# touches the repo — same rule as the Stripe secrets.
#
# Stages 7-9 are OPTIONAL and gated: they take kundalinispines.com off
# Namecheap parking and make the site live at the real domain. Skipping them
# leaves the site live only at kundalini-spines.pages.dev.

TOTAL_STAGES=9

banner "Cloudflare migration — account side"

# ──────────────────────────────────────────────────────────────────────────
stage "Prerequisite — the workflow must be on main"
say "The deploy workflow (deploy-cloudflare.yml) has to be on the main branch"
say "before anything here can run. Getting it there is a release: ask Claude"
say "to run the session-end flow and then sync main, and confirm the push."
open_url "https://github.com/kundalinispines/kundalini-spines-site/tree/main/.github/workflows"
step "Check the file list in the tab that opened: deploy-cloudflare.yml should"
step "be there, and deploy-pages.yml should be gone."
if ! confirm "Is deploy-cloudflare.yml on main?"; then
  warn "Stop here. Release the feature branch to main first, then re-run this."
  exit 1
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
say "Create the Cloudflare account (or sign in if one exists)."
open_url "https://dash.cloudflare.com/sign-up"
step "Sign up with your email. The free plan is the right one — everything"
step "this site needs (Pages, and later R2 + the Worker) starts free."
note "If you already have an account, just sign in instead."
pause "Press Enter once you're looking at the Cloudflare dashboard."

# ──────────────────────────────────────────────────────────────────────────
stage "Account ID → GitHub secret CLOUDFLARE_ACCOUNT_ID"
say "The deploy needs your account id. It's public-ish, but it still goes in"
say "a GitHub secret rather than the repo."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "On the Workers & Pages overview, find 'Account ID' in the right-hand"
step "sidebar and copy it. (It's also the hex string in the dashboard URL.)"
open_url "https://github.com/kundalinispines/kundalini-spines-site/settings/secrets/actions"
step "In the GitHub tab: New repository secret → name CLOUDFLARE_ACCOUNT_ID"
step "→ paste the account id → Add secret."
pause "Press Enter when the CLOUDFLARE_ACCOUNT_ID secret exists."

# ──────────────────────────────────────────────────────────────────────────
stage "Create the Pages project (direct upload)"
say "The project must exist before CI can deploy into it, and a direct-upload"
say "project needs one first upload — so we hand it a one-line placeholder"
say "that the first real deploy immediately replaces."
PLACEHOLDER_DIR=$(mktemp -d)/kundalini-spines-placeholder
mkdir -p "$PLACEHOLDER_DIR"
printf '<!doctype html><title>kundalini spines</title>standby\n' > "$PLACEHOLDER_DIR/index.html"
say ""
say "Placeholder folder created at:"
say "  $PLACEHOLDER_DIR"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Create application → Pages tab → 'Upload assets' (direct upload —"
step "do NOT 'Connect to Git': the allowlist only guards the direct upload)."
step "Project name: kundalini-spines   — exactly this, lowercase, with the"
step "hyphen; the workflow deploys by this name and the *.pages.dev URL is it."
step "Upload the placeholder folder above, then click Deploy site."
note "UI wording shifts occasionally; the flow is Workers & Pages → Create."
pause "Press Enter once the project kundalini-spines exists."

# ──────────────────────────────────────────────────────────────────────────
stage "API token → GitHub secret CLOUDFLARE_API_TOKEN"
say "A scoped token lets CI deploy Pages and nothing else. It is shown ONCE —"
say "paste it straight into GitHub and never anywhere else (never the repo,"
say "never a chat, never a handoff)."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → scroll to 'Custom token' → Get started."
step "Name: kundalini-spines-pages-deploy"
step "Permissions: Account · Cloudflare Pages · Edit   (that one row only)."
step "Account Resources: Include · your account."
step "Continue to summary → Create Token → copy the token."
open_url "https://github.com/kundalinispines/kundalini-spines-site/settings/secrets/actions"
step "In the GitHub tab: New repository secret → name CLOUDFLARE_API_TOKEN"
step "→ paste the token → Add secret."
pause "Press Enter when the CLOUDFLARE_API_TOKEN secret exists."

# ──────────────────────────────────────────────────────────────────────────
stage "First deploy"
say "Both secrets exist, so the workflow can run. Trigger it by hand once"
say "rather than waiting for the next push."
open_url "https://github.com/kundalinispines/kundalini-spines-site/actions/workflows/deploy-cloudflare.yml"
step "Click 'Run workflow' (branch: main) and watch the run: Assemble,"
step "accounting, leak guard, then 'Deploy to Cloudflare Pages'."
warn "If it fails at the deploy step, the usual causes are a mistyped secret"
say "name or a token missing the Pages Edit permission."
pause "Press Enter when the run is green."

# ──────────────────────────────────────────────────────────────────────────
stage "Verify the pages.dev site"
open_url "https://kundalini-spines.pages.dev"
step "The site should load — check the nav (seven items), the Album page and"
step "its three priced edition panels."
note "This URL is the site's home until the domain moves in the next stages."
if ! confirm "Continue to the DNS stages? (This is the part that takes kundalinispines.com off parking.)"; then
  note "Fine — the site stays at kundalini-spines.pages.dev. Re-run this"
  note "wizard and skip ahead when you're ready to move the domain."
  finish
  exit 0
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Add kundalinispines.com to Cloudflare"
warn "From here on you're going live at the real domain — including the"
warn "purchase page with its TEST-mode Stripe link (your recorded choice)."
say ""
open_url "https://dash.cloudflare.com/?to=/:account/add-site"
step "Enter kundalinispines.com → select the Free plan."
step "Cloudflare scans and imports the existing DNS records. DELETE the"
step "imported Namecheap parking records (the A record on the apex pointing"
step "at 162.255.119.169 and the www CNAME to parking) — they'd fight the"
step "custom-domain records the next stage creates."
step "Note the two nameservers Cloudflare assigns (…ns.cloudflare.com) —"
step "the next stage pastes them into Namecheap. Keep this tab open."
pause "Press Enter when the zone exists and you can see the two nameservers."

# ──────────────────────────────────────────────────────────────────────────
stage "Point Namecheap at Cloudflare, attach the domain"
open_url "https://ap.www.namecheap.com/domains/list/"
step "Manage next to kundalinispines.com → Nameservers → Custom DNS →"
step "enter both Cloudflare nameservers → save (the little check mark)."
note "Propagation is usually minutes but can take hours; Cloudflare emails"
note "when the zone goes Active. The parking page dies with the old"
note "nameservers — that's the point."
pause "Press Enter once Cloudflare shows the zone as Active."
say "Now attach the domain to the Pages project:"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the kundalini-spines project → Custom domains → Set up a domain →"
step "kundalinispines.com → follow through (Cloudflare creates the record)."
step "Repeat for www.kundalinispines.com so the www form works too."
step "Then load https://kundalinispines.com — the site, with a padlock."
pause "Press Enter when kundalinispines.com serves the site."

finish
say "Tell Claude the migration ran — the next session should verify the live"
say "site, retire STRIPE-SETUP.md's GitHub-Pages assumptions, and only then"
say "start the fulfilment Worker when you say go."
