#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the confirmation-email backend. Sept 1 2026.
#
# WHAT THIS SETS UP. functions/api/stripe-webhook.js emails every buyer their
# download link. It is inert until three things exist that only the owner can
# create: a Resend account that can send as kundalinispines.com, a KV namespace
# bound as ORDERS, and a Stripe webhook endpoint with its signing secret. This
# walks all three, then proves it worked.
#
# THIS WIZARD DELIBERATELY CAPTURES NOTHING. The template it was generated from
# offers ask_secret / write_env / set_secret, and none of them are used here.
# Every secret in this project lives in the Cloudflare dashboard and NOWHERE
# else — this repo is public, and STRIPE-SETUP.md section 3 has one capitalised
# rule: never in this repo. A wizard that read a whsec_ into a shell variable
# and wrote it to .env would be the exact leak the deploy workflow's guard
# exists to catch, committed by the tool meant to help. So this script opens
# the right page, tells you precisely what to paste where, and then VERIFIES
# the result over HTTP. Nothing sensitive touches this disk or this shell's
# history.
#
# EXPECT THE DASHBOARD LABELS TO HAVE MOVED. They already did once: this
# project's notes said "Settings -> Environment variables" and "Settings ->
# Functions -> R2 bucket bindings", and Cloudflare has retired both. When a
# label here disagrees with what is on your screen, trust the screen.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

SITE="https://kundalinispines.com"
CF_PAGES_PROJECT="kundalini-spines"

# probe_webhook ORIGIN — POST an unsigned request at /api/stripe-webhook and
# echo the HTTP status. SAFE AND READ-ONLY: the handler checks configuration
# and then the signature, and an unsigned body dies at the signature check
# before it reads Stripe, writes KV, or sends anything.
probe_webhook() {
  curl -s -o /dev/null -w '%{http_code}' --max-time 25 \
    -X POST "$1/api/stripe-webhook" \
    -H 'content-type: application/json' -d '{}' 2>/dev/null || printf '000'
}

# probe_verify ORIGIN — ask /api/verify about a session id that cannot exist.
# A healthy, fully configured endpoint answers 404 (Stripe said no such
# session). A 500 means it could not even ask.
probe_verify() {
  curl -s -o /dev/null -w '%{http_code}' --max-time 25 \
    "$1/api/verify?session_id=cs_live_probe000notreal" 2>/dev/null || printf '000'
}

interpret_webhook() {
  case "$1" in
    400) printf '  %s[ok] 400 bad_signature - deployed AND fully configured.%s\n' "$GREEN" "$RESET"
         note "   400 is the goal here: it means the request got all the way to"
         note "   the signature check, which it can only reach once every"
         note "   variable and the ORDERS binding are present."
         return 0 ;;
    500) printf '  %s[!!] 500 server_misconfigured - deployed, something missing.%s\n' "$RED" "$RESET"
         note "   A variable is unset, or the ORDERS KV binding is not bound, or"
         note "   the values were saved but the site has not been redeployed."
         return 1 ;;
    405|404)
         printf '  %s[!!] %s - the function is not deployed yet.%s\n' "$RED" "$1" "$RESET"
         note "   Stage 6 (the release) has not happened, or has not finished."
         note ""
         note "   405 rather than 404 is not a mistake and is worth knowing:"
         note "   Cloudflare Pages serves static assets for GET and HEAD only,"
         note "   so a POST to a path with no Function attached comes back"
         note "   Method Not Allowed, never Not Found. Measured against the live"
         note "   site on Sept 1 2026, before this endpoint shipped - this line"
         note "   said 404 until that probe corrected it."
         return 1 ;;
    000) printf '  %s[!!] no answer - network, DNS, or the site is down.%s\n' "$RED" "$RESET"
         return 1 ;;
    *)   printf '  %s[??] unexpected status %s%s\n' "$YELLOW" "$1" "$RESET"
         return 1 ;;
  esac
}

banner "Kundalini Spines - the confirmation email backend"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Resend - account, and the sending domain"
warn "Correction to the opening screen, which is shared boilerplate: this"
warn "wizard does NOT capture or remember any value you copy. Every secret"
warn "goes into the Cloudflare dashboard by hand, and nothing is written to"
warn "this disk. Stopping and re-running is still safe - each stage can be"
warn "skipped if you have already done it."
say ""
say "Resend is what actually puts mail in the buyer's inbox."
say ""
if confirm "Already have Resend with kundalinispines.com verified?"; then
  RESEND_ALREADY=yes
  note "Good - skipping ahead. Stage 2 can still check the DNS looks right."
else
  RESEND_ALREADY=no
  open_url "https://resend.com/signup"
  step "Create the account. The free tier is 3,000 emails/month, far above this."
  pause "Signed in?"
  open_url "https://resend.com/domains"
  step "Click Add Domain."
  step "Enter:  kundalinispines.com"
  step "Pick the region closest to your buyers, then Add."
  say ""
  warn "Do NOT close that page - the next stage needs the records it shows."
  note "You cannot send from gmail.com: a sender domain has to be one you can"
  note "prove you own. That is why the album mail comes FROM"
  note "orders@kundalinispines.com and REPLIES go to your gmail."
  pause "Domain added, DNS records on screen?"
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare DNS - publish Resend's records"
say "Resend just showed you a handful of DNS records. They go in Cloudflare,"
say "which already hosts DNS for kundalinispines.com."
say ""
if [[ "$RESEND_ALREADY" == "no" ]]; then
  open_url "https://dash.cloudflare.com/?to=/:account/kundalinispines.com/dns"
  step "For EACH record Resend listed: Add record, and copy it across exactly"
  step "  - Type, Name and Content, character for character."
  say ""
  note "Two things that waste an afternoon if you get them wrong:"
  note "  - Leave the orange cloud OFF (DNS only). These are TXT and MX"
  note "    records; proxying does not apply and turning it on breaks them."
  note "  - If a record Name looks like it already exists, do not overwrite it."
  note "    An existing MX or SPF record belongs to something, and clobbering"
  note "    it silently stops other mail. Ask before replacing one."
  say ""
  step "Back in Resend, click Verify DNS Records."
  note "Cloudflare publishes in seconds, but Resend can take a few minutes to"
  note "agree. Pending is normal; come back to it."
  pause "Records added and Verify pressed?"
fi

if confirm "Check that a DKIM record has actually published?"; then
  say ""
  ask DKIM_NAME "Name of Resend's DKIM record (e.g. resend._domainkey):"
  if [[ -n "${DKIM_NAME:-}" ]]; then
    LOOKUP="$DKIM_NAME"
    case "$LOOKUP" in
      *kundalinispines.com) : ;;
      *) LOOKUP="$DKIM_NAME.kundalinispines.com" ;;
    esac
    say ""
    note "looking up TXT $LOOKUP"
    FOUND=""
    if command -v dig >/dev/null 2>&1; then
      FOUND=$(dig +short TXT "$LOOKUP" 2>/dev/null || true)
    elif command -v nslookup >/dev/null 2>&1; then
      FOUND=$(nslookup -type=TXT "$LOOKUP" 2>/dev/null | grep -i 'text =' || true)
    else
      note "no dig or nslookup here - skipping the check."
    fi
    if [[ -n "$FOUND" ]]; then
      printf '  %s[ok] published%s\n' "$GREEN" "$RESET"
    else
      warn "nothing came back yet. Usually propagation, not a mistake."
      note "Give it a few minutes. If it is still empty in 15, the record Name"
      note "is probably doubled - Cloudflare appends the zone to a name that"
      note "already ended in it, giving resend._domainkey.kundalinispines.com"
      note ".kundalinispines.com. Check the full name shown in Cloudflare."
    fi
  fi
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Resend - the API key, into Cloudflare"
say "One key, pasted straight into Cloudflare. It is shown ONCE."
say ""
open_url "https://resend.com/api-keys"
step "Create API Key. Name it something like kundalini-spines-pages."
step "Permission: Sending access is enough. It does not need full access."
step "Copy the key (starts re_). This is the only time you will see it."
say ""
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$CF_PAGES_PROJECT/settings"
step "Settings -> Variables and Secrets -> Add."
step "Variable name:  RESEND_API_KEY"
step "SET THE TYPE DROPDOWN TO Secret BEFORE PASTING THE VALUE."
step "Paste the key. Save."
say ""
warn "A Secret cannot be read back afterwards. That is the point, and it also"
warn "means a typo in one is completely invisible. If the webhook later answers"
warn "500, re-enter it rather than trying to inspect it."
pause "RESEND_API_KEY saved as a Secret?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare - the KV namespace, bound as ORDERS"
say "This is where order records live: one per sale, so a redelivered webhook"
say "cannot email the same buyer twice, and a lost link can be looked up."
say ""
open_url "https://dash.cloudflare.com/?to=/:account/workers/kv/namespaces"
step "Create a namespace. Name:  kundalini-spines-orders"
pause "Namespace created?"
say ""
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$CF_PAGES_PROJECT/settings"
step "Settings -> Bindings -> Add -> KV namespace."
step "Variable name:  ORDERS     (exactly that - the code looks it up by name)"
step "Namespace: the one you just made. Save."
say ""
warn "Bindings are NOT variables. They live on a different screen and will not"
warn "appear under Variables and Secrets. This is the step people skip."
note "Records are kept with no expiry, on purpose: the download window closes"
note "in 72 hours, but did-this-person-buy-the-album outlives it by years."
pause "ORDERS bound?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Stripe - the webhook endpoint and its signing secret"
say "This is the part that makes Stripe tell the server about a sale, instead"
say "of the server hoping the buyer's browser made it back."
say ""
open_url "https://dashboard.stripe.com/webhooks"
warn "Check you are in LIVE mode, not Test. The toggle is top-right."
step "Add destination.  (Stripe renamed webhook endpoints to event"
step "  destinations; this is the button that used to say Add endpoint.)"
step "Leave the scope on Your account, and take the default API version."
step "Select events - you need BOTH of these:"
step "     checkout.session.completed"
step "     checkout.session.async_payment_succeeded"
say ""
note "Why both: for a card the first fires the moment money settles. For a slow"
note "method it fires with payment_status still unpaid, and the money lands"
note "later under the second. Subscribing to only the first would email nothing"
note "to exactly the buyers who waited longest."
say ""
step "Destination type: Webhook endpoint (not Amazon EventBridge)."
step "Endpoint URL:  $SITE/api/stripe-webhook"
step "Create it, then reveal the Signing secret and copy it (starts whsec_)."
note "The eye icon on the destination page reveals that secret again any"
note "time. It is not shown only once, whatever older writing here says."
say ""
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$CF_PAGES_PROJECT/settings"
step "Settings -> Variables and Secrets -> Add."
step "Variable name:  STRIPE_WEBHOOK_SECRET"
step "Type: Secret.  Paste. Save."
say ""
note "That secret is the ONLY thing separating a real Stripe delivery from a"
note "stranger POSTing to a public URL. Nothing else authenticates this."
pause "STRIPE_WEBHOOK_SECRET saved as a Secret?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Release - because none of it is live until you deploy"
warn "Cloudflare Pages applies variables and bindings AT DEPLOY TIME."
say "Everything you just saved is sitting there inert. The running site is"
say "still the previous deployment, which has none of it."
say ""
say "A release is your call, every time, so this wizard will not do it."
say "When you are ready, from the repo:"
say ""
printf '      %sgit push origin feature/spine-ui-v2:main%s\n' "$BOLD" "$RESET"
say ""
note "That push triggers deploy-cloudflare.yml, which assembles the allowlisted"
note "public files and uploads them. functions/ rides along automatically -"
note "wrangler picks it up from the repo root, which is why it is not in the"
note "allowlist and must never be moved into _site."
say ""
warn "Deploy propagation has been measured between 8 and 90 seconds here. Two"
warn "checks have already been mistaken for failed deploys when they were only"
warn "early. Give it two minutes before diagnosing anything."
pause "Released, and given it a couple of minutes?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify - prove it, do not assume it"
say "Probing the live endpoints. Nothing here sends mail or moves money."
say ""
note "POST $SITE/api/stripe-webhook  (unsigned)"
WEBHOOK_CODE=$(probe_webhook "$SITE")
WEBHOOK_OK=yes
interpret_webhook "$WEBHOOK_CODE" || WEBHOOK_OK=no
say ""
note "GET  $SITE/api/verify  (with an impossible session id)"
VERIFY_CODE=$(probe_verify "$SITE")
case "$VERIFY_CODE" in
  404) printf '  %s[ok] 404 not_found - verify is healthy and reaching Stripe.%s\n' "$GREEN" "$RESET" ;;
  500) printf '  %s[!!] 500 - verify cannot reach its configuration.%s\n' "$RED" "$RESET" ;;
  000) printf '  %s[!!] no answer.%s\n' "$RED" "$RESET" ;;
  *)   printf '  %s[??] unexpected status %s%s\n' "$YELLOW" "$VERIFY_CODE" "$RESET" ;;
esac
say ""
if [[ "$WEBHOOK_CODE" == "400" ]]; then
  say "Now the same question, asked from Stripe's side."
  open_url "https://dashboard.stripe.com/webhooks"
  step "Open your endpoint, then Send test event -> checkout.session.completed."
  say ""
  warn "EXPECT 200 WITH THE BODY not_found. That is SUCCESS, not a failure."
  note "A test event names a test-mode session, and your live secret key cannot"
  note "read one - Stripe API keys are mode-scoped. A 200 proves the URL"
  note "resolves, the signature verified against your whsec, and the secrets"
  note "are readable. It is everything except proof that mail sends."
  pause "Test event returned 200?"
else
  warn "Skipping the Stripe test event - fix the probe above first."
  note "Most common cause by far: values saved, but the site not redeployed"
  note "since. Re-run stage 6."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The real test - one live purchase, refunded"
say "There is no way around this one, and it is worth understanding why."
say ""
note "A test-mode purchase CANNOT validate this setup. Stripe keys are"
note "mode-scoped: the live STRIPE_SECRET_KEY cannot read a test session, so a"
note "test purchase returns not_found. Testing in test mode would mean swapping"
note "BOTH the secret key and the price id, then re-pasting the live secret"
note "blind afterwards, because a Secret cannot be read back. The real test is"
note "a real purchase, refunded after. This project has done exactly that once."
say ""
open_url "$SITE/purchase.html"
step "Buy the Digital Edition with a real card."
step "Confirm the success page shows both download buttons."
step "Confirm the note under them now says a copy has been EMAILED to you."
step "  That sentence only appears when the server can see the mail went."
step "Check the inbox: the mail carries the success URL, the deadline and the"
step "  order reference."
step "Click the link FROM THE EMAIL, in a different browser if you can. That"
step "  is the whole point of this build - the buyer's way back."
say ""
step "Then refund it: Stripe -> Payments -> the payment -> Refund."
step "Reload the success page. The download must now be refused."
say ""
warn "If anything goes wrong with a sale, the 20-second fix is to revert"
warn "checkoutUrl in js/purchase-checkout.js to the test link and release."
warn "That closes sales and breaks nothing for anyone who already bought."
pause "Done?"

finish
note "What you set up:"
note "  Resend     - sending as orders@kundalinispines.com"
note "  KV ORDERS  - one record per sale, keyed order:<session id>"
note "  Stripe     - checkout.session.completed + async_payment_succeeded"
note ""
note "Reference: STRIPE-SETUP.md sections 3 and 5."
note "If a buyer ever loses their link, their order is in the KV namespace"
note "under order:<their session id>, and Stripe's dashboard finds that id"
note "from their email address."
printf '\n'
exit 0
