#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# NOTHING HERE IS WRITTEN TO DISK, AND THAT IS DELIBERATE. The library above
# ships write_env/set_secret helpers and this wizard calls neither. Every
# secret in this procedure is typed by the human into the CLOUDFLARE dashboard,
# which is the only place that needs it; a local .env would be a second copy of
# a live Stripe key sitting in the project folder for no benefit. .env is
# gitignored here, so it would not be committed — but "it would not have been
# committed" is a thin reason to keep a secret around. STRIPE-SETUP.md §3 says
# never in this repo, and that includes ignored files.
TOTAL_STAGES=10

banner "Kundalini Spines — R2 album download"

# ──────────────────────────────────────────────────────────────────────────
stage "Before anything — what this does and does not do"
say "This provisions the storage and credentials behind the digital album"
say "download. It is all dashboard work on your Cloudflare and Stripe"
say "accounts — no Node, no npm, no wrangler needed."
printf '\n'
say "When you finish, the site will still NOT be selling. The buy button"
say "stays on the test Payment Link until you deliberately swap it, which"
say "is the very last step and is not in this wizard."
printf '\n'
warn "Cloudflare Pages only picks up new variables and bindings on a NEW"
warn "deployment. So the order is: set everything up here FIRST, then"
warn "release, then verify. Releasing before this is done just gives you"
warn "an endpoint that 500s."
printf '\n'
note "Have ready: your Cloudflare login, your Stripe login, and the album"
note "ZIP on this machine."
pause "Ready?"

# ──────────────────────────────────────────────────────────────────────────
stage "Create the private R2 bucket"
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "Click 'Create bucket'."
step "Name it:  kundalini-spines-album"
step "Location: leave Automatic. Storage class: leave Standard."
step "Click 'Create bucket'."
printf '\n'
warn "DO NOT enable a public r2.dev URL, and DO NOT connect a custom domain"
warn "to this bucket — not now, not later. A public bucket URL is exactly"
warn "the unsigned, unrevocable address the project has forbidden since"
warn "Aug 20: a hard-to-guess path is not protection, it is a URL, and URLs"
warn "get shared. The whole design assumes the ONLY way in is the binding"
warn "you set up two stages from now."
printf '\n'
note "If you land on a bucket page with an 'Allow Access' or 'Public"
note "Development URL' panel — leave it alone. Bucket stays private."
pause "Bucket created and still private?"

# ──────────────────────────────────────────────────────────────────────────
stage "Upload the MP3 zip — the one the dashboard can take"
say "There are two files to get into the bucket:"
printf '\n'
printf '      %sKundaliniSpines_RiseUp_MP3.zip%s    271 MB\n' "$BOLD" "$RESET"
printf '      %sKundaliniSpines_RiseUp_WAV.zip%s  1,395 MB\n\n' "$BOLD" "$RESET"
say "This stage does the MP3. The WAV needs a different tool and gets the"
say "whole of the next stage."
printf '\n'
step "On your bucket's page, click 'Upload' → 'Select from computer'."
step "Pick KundaliniSpines_RiseUp_MP3.zip from"
step "  Desktop\\RiseUp_Digital_Delivery\\"
step "Wait for it to finish."
printf '\n'
warn "DO NOT RENAME IT. The code defaults to these exact filenames, so"
warn "leaving them alone means there is nothing to configure in stage 7."
printf '\n'
note "If the browser upload fails on this one too, skip it — stage 4 uploads"
note "both files at once and makes this stage unnecessary."
pause "MP3 uploaded (or skipped)?"

# ──────────────────────────────────────────────────────────────────────────
stage "Upload the WAV zip — 1.4 GB, so not through the browser"
say "The dashboard uploads a file in a single request. At 1,395 MB the WAV"
say "set is past what that can carry, which is why it failed. This is a"
say "limit of the upload METHOD, not of R2 — R2 holds objects up to 5 TB."
printf '\n'
say "Large files need a multipart upload. Cloudflare's own recommendation"
say "is rclone: one Windows .exe, no Node, no npm, no installer. It splits"
say "the file automatically and resumes if the connection drops."
printf '\n'
step "1. Download rclone for Windows (AMD64):"
open_url "https://rclone.org/downloads/"
step "   Unzip it anywhere — Desktop is fine. You want rclone.exe."
printf '\n'
step "2. Create an R2 API token:"
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "   'Create API token' → Permissions: Object Read & Write"
step "   → scope it to the kundalini-spines-album bucket → Create."
step "   Copy the Access Key ID and Secret Access Key, and your Account ID"
step "   from the R2 overview page."
printf '\n'
warn "That token is a write credential for your bucket. It goes into the"
warn "rclone config on your machine and nowhere near this repo."
printf '\n'
pause "Got rclone.exe and the three values?"

printf '\n'
say "3. Configure rclone. In PowerShell, from the folder holding rclone.exe:"
printf '\n'
printf '      %s.\\rclone.exe config%s\n\n' "$BOLD" "$RESET"
step "   n (new remote)  →  name it:  r2"
step "   Storage:  s3        Provider:  Cloudflare"
step "   access_key_id / secret_access_key: the two you just copied"
step "   region:  auto"
step "   endpoint:  https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
step "   bucket_object_lock_enabled: press Enter (leave it false)"
printf '\n'
say "Then three prompts in a row that people get wrong, because the answer"
say "changes at each one:"
printf '\n'
printf '      %sEdit advanced config?%s        y/n>  →  %sn%s\n' "$DIM" "$RESET" "$BOLD" "$RESET"
printf '      %sKeep this "r2" remote?%s      y/e/d> →  %sy%s\n' "$DIM" "$RESET" "$BOLD" "$RESET"
printf '      %sthe main menu%s          e/n/d/r/c/s/q> →  %sq%s\n\n' "$DIM" "$RESET" "$BOLD" "$RESET"
warn "q ONLY works on that last one. An earlier draft of this wizard said"
warn "'leave the rest blank, then q to quit', which reads as though q ends"
warn "the whole thing at any point. It does not — the sub-prompts accept"
warn "only the letters they list, and q there just re-asks the question."
printf '\n'
pause "Remote 'r2' configured?"

printf '\n'
say "4. Upload. This is the command — it does both files, so it also covers"
say "   the MP3 if the browser upload failed:"
printf '\n'
printf '      %s.\\rclone.exe copy "$HOME\\Desktop\\RiseUp_Digital_Delivery" r2:kundalini-spines-album --progress%s\n\n' "$BOLD" "$RESET"
note "rclone skips files already present and identical, so re-running it is"
note "safe and it will not re-send the MP3 if it is already there."
note "Expect the WAV to take a while — it shows a live progress bar. If it"
note "drops, run the same command again and it picks up where it stopped."
printf '\n'
pause "Both files uploaded?"

printf '\n'
say "5. Confirm what actually landed:"
printf '\n'
printf '      %s.\\rclone.exe ls r2:kundalini-spines-album%s\n\n' "$BOLD" "$RESET"
say "You want exactly these two lines, sizes in bytes:"
printf '\n'
printf '      %s1463052288 KundaliniSpines_RiseUp_WAV.zip%s\n' "$DIM" "$RESET"
printf '      %s 284489728 KundaliniSpines_RiseUp_MP3.zip%s\n\n' "$DIM" "$RESET"
note "Approximate — yours will differ a little. What matters is that both"
note "names are present and neither size is suspiciously small, which is"
note "what a half-finished upload looks like."
printf '\n'
ask BUCKET_LISTING_OK "Are both files listed, at full size? (yes/no):"
case "$BUCKET_LISTING_OK" in
  [Yy]*) say "Good." ;;
  *) warn "Do not go further until both are in the bucket. A buyer who pays"
     warn "and hits a missing file is the one failure here that costs money."
     SKIPPED+=("Finish uploading both zips to kundalini-spines-album")
     pause "Noted — continuing so you can finish the rest." ;;
esac

# ──────────────────────────────────────────────────────────────────────────
stage "Bind the bucket to the Pages project"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the kundalini-spines project."
step "Settings → Bindings → Add → R2 bucket."
step "Variable name:  ALBUM_BUCKET"
step "R2 bucket:      kundalini-spines-album"
step "Save."
printf '\n'
note "The variable name is case-sensitive and must be exactly ALBUM_BUCKET —"
note "functions/api/download.js looks it up by that name and logs"
note "'R2 binding ALBUM_BUCKET is not bound' when it is missing."
printf '\n'
warn "IF YOU CANNOT FIND 'Functions' IN THE SETTINGS — you are not lost, the"
warn "dashboard moved. Bindings used to live under Settings → Functions →"
warn "R2 bucket bindings, and that section no longer exists; it is now just"
warn "Settings → Bindings. Corrected Aug 31 2026 on the owner's first real"
warn "run of this wizard, which sent them hunting for a screen Cloudflare"
warn "had already retired."
pause "Binding saved?"

# ──────────────────────────────────────────────────────────────────────────
stage "Stripe — the live price ID"
say "You need the live Price ID for the \$20 Digital Edition. The code checks"
say "it against every order, so a paid \$42 Deluxe cannot unlock the album."
open_url "https://dashboard.stripe.com/products"
step "Make sure you are in LIVE mode (the test-mode toggle is off)."
step "Open the Rise Up — Digital Album product, or create it: \$20 USD,"
step "  one-time payment."
step "In the Pricing section, click the price, and copy its API ID."
printf '\n'
note "It starts with price_ — NOT prod_ (that is the product) and NOT"
note "plink_ (that is the Payment Link). Getting this wrong makes every"
note "real order fail the product check with 'wrong_product'."
printf '\n'
ask PRICE_ID_DIGITAL "Paste the price ID (price_...):"
case "$PRICE_ID_DIGITAL" in
  price_*) say "Looks right." ;;
  prod_*)  warn "That is a PRODUCT id. Go back and open the price itself." ;;
  plink_*) warn "That is a PAYMENT LINK id. You need the price under it." ;;
  *)       warn "That does not look like a price ID. Double-check before saving it." ;;
esac
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Generate the download signing key"
say "This signs the short-lived token behind the Download button. It is not"
say "a Stripe credential — it is yours, and nothing outside Cloudflare ever"
say "needs to know it."
printf '\n'
if command -v openssl >/dev/null 2>&1; then
  SIGNING_KEY=$(openssl rand -base64 48 | tr -d '\n')
elif command -v python >/dev/null 2>&1; then
  SIGNING_KEY=$(python -c "import secrets;print(secrets.token_urlsafe(48))")
elif command -v python3 >/dev/null 2>&1; then
  SIGNING_KEY=$(python3 -c "import secrets;print(secrets.token_urlsafe(48))")
else
  SIGNING_KEY=""
fi

if [[ -n "$SIGNING_KEY" ]]; then
  say "Here is a fresh one. Copy it now — this wizard does not save it"
  say "anywhere, and the next stage is where it gets pasted."
  printf '\n%s  %s%s\n\n' "$BOLD" "$SIGNING_KEY" "$RESET"
else
  warn "No openssl or python found to generate one."
  warn "Use any long random string — 40+ characters, from a password"
  warn "manager's generator. It just has to be unguessable."
fi
note "Rotating this later is harmless: it invalidates outstanding download"
note "tokens and nothing else. Buyers simply reload and re-verify."
pause "Copied?"

# ──────────────────────────────────────────────────────────────────────────
stage "Set the environment variables"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
say "Same project, same Settings page as the binding you just saved:"
say "Settings → Variables and Secrets → Add."
say "Three of them. Encrypt the first two."
note "Also renamed by Cloudflare — this was 'Environment variables' when"
note "this wizard was written. Secrets and plain variables now share one"
note "screen, and Encrypt is what separates them."
printf '\n'
step "1.  STRIPE_SECRET_KEY   = your LIVE secret key (sk_live_...)"
say "        Get it from https://dashboard.stripe.com/apikeys — live mode,"
say "        'Reveal live key'.  ── click ENCRYPT ──"
printf '\n'
step "2.  DOWNLOAD_SIGNING_KEY = the string from the previous stage"
say "        ── click ENCRYPT ──"
printf '\n'
step "3.  PRICE_ID_DIGITAL     = $PRICE_ID_DIGITAL"
say "        Not secret. Leave it as plain text."
printf '\n'
note "No object-key variables needed: the code defaults to"
note "KundaliniSpines_RiseUp_MP3.zip and KundaliniSpines_RiseUp_WAV.zip,"
note "which is why the last two stages told you not to rename anything."
note "Only set ALBUM_OBJECT_KEY_MP3 / ALBUM_OBJECT_KEY_WAV if you did."
printf '\n'
step "Click 'Save'."
printf '\n'
warn "Encrypt means you cannot read the value back afterwards. That is the"
warn "point — but it also means a typo is invisible. If verification fails"
warn "at the last stage with 'server_misconfigured', re-enter these rather"
warn "than trying to inspect them."
pause "All variables saved?"

# ──────────────────────────────────────────────────────────────────────────
stage "Release, so the settings take effect"
say "Everything above is now configured but NOT live: Pages applies new"
say "variables and bindings to the next deployment, not to the running one."
printf '\n'
say "The code itself is on feature/spine-ui-v2 and has not been released"
say "either. One release does both."
printf '\n'
warn "A release DEPLOYS. This is the owner's call and this wizard will not"
warn "make it for you. Run it yourself when you are ready:"
printf '\n      %sgit push origin feature/spine-ui-v2:main%s\n\n' "$BOLD" "$RESET"
say "This is a low-risk release: it ships the new success page and the two"
say "functions, but the buy button still points at the TEST Payment Link,"
say "so no real money can move yet."
printf '\n'
note "The deploy takes about 20 seconds. Watch it at:"
note "https://github.com/kundalinispines/kundalini-spines-site/actions"
pause "Press Enter when the deploy has finished (or to skip and verify later)"

# ──────────────────────────────────────────────────────────────────────────
stage "Verify the wiring"
say "One request proves the Functions compiled, the secret key works, and"
say "the product check is live — without spending a cent."
printf '\n'
VERIFY_URL="https://kundalinispines.com/api/verify?session_id=cs_test_notarealsession"
if command -v curl >/dev/null 2>&1; then
  say "Calling: $VERIFY_URL"
  printf '\n'
  RESPONSE=$(curl -s -m 20 "$VERIFY_URL" || echo "")
  printf '  %s%s%s\n\n' "$DIM" "${RESPONSE:-<no response>}" "$RESET"
  case "$RESPONSE" in
    *not_found*)
      printf '  %s✓ WIRED CORRECTLY.%s\n' "$GREEN" "$RESET"
      say "Stripe was reached, it did not recognise that fake session, and"
      say "the function said so in JSON. That is exactly right." ;;
    *server_misconfigured*)
      warn "Functions are live but an environment variable is missing or"
      warn "mistyped. Re-do stage 7. If it persists, the R2 binding from"
      warn "stage 4 may not have saved." ;;
    *upstream*)
      warn "The function ran but could not use the Stripe key. Check that"
      warn "STRIPE_SECRET_KEY is a LIVE key and was pasted whole." ;;
    "")
      warn "No response. Either the deploy has not finished, or the site is"
      warn "unreachable from here." ;;
    *"<!DOCTYPE"*|*"<html"*)
      warn "Got an HTML page instead of JSON — Cloudflare did not pick up"
      warn "the functions/ directory. Check that functions/ is at the REPO"
      warn "ROOT (not inside _site) and that the deploy actually ran." ;;
    *)
      warn "Unexpected response above. Nothing is broken on the buyer's"
      warn "side — the buy button is still on the test link." ;;
  esac
else
  say "curl not found. Paste this into a browser instead:"
  printf '\n      %s%s%s\n\n' "$BOLD" "$VERIFY_URL" "$RESET"
  say "You want JSON reading  {\"ok\":false,\"error\":\"not_found\"}"
  say "An HTML 404 page means the functions did not deploy."
fi
printf '\n'
pause

finish
say "What is done: bucket, ZIP, binding, price ID, signing key, variables."
printf '\n'
say "What is NOT done, and is deliberately still yours to trigger:"
step "A test-mode purchase end to end (STRIPE-SETUP.md §7 checklist)."
step "Swapping the live Payment Link into js/purchase-checkout.js line ~101."
step "The release that opens real sales."
printf '\n'
warn "Do not swap the live link until a test purchase has downloaded a real"
warn "file. The failure you are guarding against is a buyer paying \$20 and"
warn "getting an error panel."
printf '\n'
