#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Kundalini Spines — connect the Digital Edition to a Stripe Payment Link.
#
# WHAT THIS WIZARD DOES NOT DO, ON PURPOSE:
#   - It never asks for a Stripe SECRET key and never writes one anywhere.
#     Payment Links need no key in this repo at all; the only value captured
#     is the buy.stripe.com URL, which is public by design and belongs in
#     public JavaScript. If any step ever seems to want an sk_ or whsec_
#     value, you are on the wrong path — stop and read STRIPE-SETUP.md §1.
#   - It writes no .env and sets no GitHub secret. There is nothing to put in
#     one. The wizard library above supports both; this wizard uses neither.
#
# Written Aug 27 2026. Dashboard labels quoted below were taken from
# docs.stripe.com/payment-links/create and /post-payment on that date, not
# from memory. Stripe moves its UI; if a label has changed, trust the intent
# described in the step and not the exact wording.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# On Git Bash, pwd gives /c/Users/... which a native Windows python cannot open.
# MSYS usually rewrites it on the way into the environment, but that is a
# heuristic and it is not worth trusting for a file this script overwrites.
# cygpath -m gives C:/Users/... which is valid to BOTH bash and Windows python;
# -w is not, because its backslashes are escapes to bash. No-op off Windows.
if command -v cygpath >/dev/null 2>&1; then
  REPO_ROOT="$(cygpath -m "$REPO_ROOT")"
fi
CONFIG_FILE="$REPO_ROOT/js/purchase-checkout.js"
PY="$(command -v python || command -v python3 || true)"

# current_url — the digital edition's checkoutUrl as it stands in the config,
# or the literal string "null". Read with python so the answer comes from the
# same parse the writer uses, rather than from a grep that could drift.
current_url() {
  [[ -n "$PY" ]] || { printf 'null'; return; }
  CONFIG_FILE="$CONFIG_FILE" "$PY" - <<'PYEOF' 2>/dev/null || printf 'null'
import os, re, io
p = os.environ["CONFIG_FILE"]
src = io.open(p, "rb").read().decode("utf-8")
m = re.search(r"id:\s*'digital'.*?checkoutUrl:\s*([^\n]+?)\s*\n", src, re.S)
print(m.group(1).rstrip(",").strip() if m else "null")
PYEOF
}

# write_checkout_url URL — put URL into the digital edition's checkoutUrl slot.
# Scoped to the digital block so the deluxe and artifact nulls are untouched,
# asserts exactly one match before writing, and backs the file up first. Binary
# read / explicit-utf-8 decode / binary write, which is this project's rule for
# JS and HTML — a text-mode round trip mangles the em dashes in this file.
write_checkout_url() {
  local url="$1"
  if [[ -z "$PY" ]]; then
    warn "no python on PATH — cannot edit the config safely."
    SKIPPED+=("paste the URL into js/purchase-checkout.js by hand: checkoutUrl: '$url'")
    return 1
  fi
  cp "$CONFIG_FILE" "$CONFIG_FILE.bak"
  if KS_URL="$url" CONFIG_FILE="$CONFIG_FILE" "$PY" - <<'PYEOF'
import os, re, io, sys
p   = os.environ["CONFIG_FILE"]
url = os.environ["KS_URL"]
src = io.open(p, "rb").read().decode("utf-8")

# Anchor on the digital block only: from its id to the end of that object.
block = re.search(r"(\{\s*\n\s*id:\s*'digital'.*?\n\s*\})", src, re.S)
if not block:
    sys.stderr.write("could not find the digital edition block\n"); sys.exit(1)
old = block.group(1)
new, n = re.subn(r"(checkoutUrl:\s*)(?:null|'[^']*'|\"[^\"]*\")", r"\1'%s'" % url, old)
if n != 1:
    sys.stderr.write("expected exactly 1 checkoutUrl in the digital block, found %d\n" % n)
    sys.exit(1)
io.open(p, "wb").write(src.replace(old, new, 1).encode("utf-8"))
PYEOF
  then
    printf '  %s✓ wrote%s checkoutUrl → js/purchase-checkout.js %s(backup: purchase-checkout.js.bak)%s\n' \
      "$GREEN" "$RESET" "$DIM" "$RESET"
    return 0
  else
    warn "the edit failed and nothing was written. Your backup is intact."
    mv "$CONFIG_FILE.bak" "$CONFIG_FILE"
    SKIPPED+=("paste the URL into js/purchase-checkout.js by hand: checkoutUrl: '$url'")
    return 1
  fi
}

banner "Kundalini Spines — connect the Digital Edition to Stripe"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — where you are, and what is safe"

say "Checking the working copy before anything touches it."
printf '\n'

if [[ -n "$PY" ]]; then
  note "python:   $PY"
else
  warn "python not found — stage 4 will fall back to a manual paste."
fi

BRANCH="$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null || echo '?')"
note "repo:     $REPO_ROOT"
note "branch:   $BRANCH"
if [[ "$BRANCH" != "feature/spine-ui-v2" ]]; then
  warn "expected feature/spine-ui-v2. Stop unless you know why you are elsewhere."
fi

if [[ -n "$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null)" ]]; then
  warn "the working tree has uncommitted changes."
  note "This wizard edits js/purchase-checkout.js. Commit or set aside first so"
  note "the URL arrives as its own reviewable change."
else
  note "tree:     clean"
fi

printf '\n'
note "current digital checkoutUrl: $(current_url)"
printf '\n'
say "The only value this wizard captures is a public buy.stripe.com URL."
warn "If anything ever asks you for a key starting sk_ or whsec_, that is the"
note "  wrong path for this site. Read STRIPE-SETUP.md section 1 and stop."
printf '\n'
confirm "Ready to go?" || { printf '\n'; note "Nothing changed."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Stripe — create the product and its \$20 price, in TEST mode"

say "Opening the Payment Links creator in TEST mode. The /test/ in the URL is"
say "what puts you there; check the Dashboard also shows a test/sandbox badge."
open_url "https://dashboard.stripe.com/test/payment-links/create"
printf '\n'
step "Click '+ New' if the creator is not already open."
step "Leave the pricing model on the products option, not 'Customers choose"
step "  what to pay' — this is a fixed-price album."
step "Click '+ Add a new product'."
step "Name it exactly:  Rise Up — Digital Edition"
step "Price:            20.00   Currency: USD   Type: One-time"
step "Click 'Add product'."
printf '\n'
note "Why \$20: the owner set it on Aug 27 2026 as the base of the ladder."
note "Deluxe (\$42) and Artifact (from \$75) are NOT being connected today —"
note "they need size, variant and numbering, which a Payment Link cannot carry."
note "See STRIPE-SETUP.md section 1, option (b)."
printf '\n'
warn "Do NOT turn on shipping-address collection. The Digital Edition is a"
note "  download; asking for an address would be collecting data you have no"
note "  use for and no page explaining."
printf '\n'
pause "Product added? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Stripe — leave the confirmation page alone, then copy the link"

say "This is the step that matters most, and the instruction is to do nothing."
printf '\n'
step "Find the 'After the payment' section of the link creator."
step "Under 'Confirmation page', LEAVE THE DEFAULT selected — the Stripe-hosted"
step "  message. Do NOT choose the redirect option."
printf '\n'
warn "Why not redirect: this site's purchase-success.html is not deployed."
note "  GitHub Pages builds from main (.github/workflows/deploy-pages.yml), and"
note "  main has no purchase pages at all — they live only on this branch, which"
note "  is 169 commits ahead. A redirect today would land a paying customer on a"
note "  404. Stripe's own confirmation page is honest and it works."
printf '\n'
note "This is not a one-way door. 'After the payment' can be edited on an"
note "existing link, so when V2 ships you set the redirect to:"
note "  https://kundalinispines.com/purchase-success.html?session_id={CHECKOUT_SESSION_ID}"
note "and this same link starts using the branded page. No new link, no code change."
printf '\n'
step "Click 'Create link'."
step "Copy the URL it gives you — it looks like https://buy.stripe.com/test_..."
printf '\n'

while true; do
  ask_url_input=""
  printf '  %sPaste the Payment Link URL:%s ' "$BOLD" "$RESET"
  read -r ask_url_input || true
  if [[ -z "$ask_url_input" ]]; then
    warn "empty — paste the URL, or Ctrl-C to stop."
    continue
  fi
  case "$ask_url_input" in
    "#"|""|"http://"*)
      warn "that is not a usable checkout URL. A '#' or a bare http:// link"
      note "  would send a paying visitor to a dead page — the exact failure the"
      note "  null in the config exists to prevent."
      continue ;;
    https://buy.stripe.com/*)
      break ;;
    https://*)
      warn "that is https but not buy.stripe.com."
      note "  Legitimate if you have put a Payment Link on a custom domain."
      confirm "Use it anyway?" && break || continue ;;
    *)
      warn "must start with https://"
      continue ;;
  esac
done
PAYMENT_LINK_URL="$ask_url_input"
case "$PAYMENT_LINK_URL" in
  *test_*) note "looks like a TEST link — good, that is what this stage wanted." ;;
  *)       warn "this does NOT look like a test link. If you are in live mode,"
           note "  a real card will really be charged. Ctrl-C now if that is a surprise." ;;
esac
printf '\n'
pause "Press Enter to write it into the site."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Write the URL into the site's config"

say "One slot changes: the digital edition's checkoutUrl in"
note "  js/purchase-checkout.js"
say "Deluxe and Artifact keep their nulls and stay honestly closed."
printf '\n'
write_checkout_url "$PAYMENT_LINK_URL" || true
printf '\n'
note "now reads: $(current_url)"
printf '\n'
note "That single value is the whole wiring. start() in that file already knows"
note "what to do with it — it is a navigation, not a fetch: no key, no CORS, no"
note "SDK. Nothing else in the repo needed changing."
printf '\n'
pause "Press Enter to test it."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Test the whole path with a test card"

say "Start the site's own server. NOT python -m http.server — that one answers"
say "media requests without Accept-Ranges and silently breaks video seeking."
printf '\n'
note "  cd \"$REPO_ROOT\" && python scripts/serve.py"
printf '\n'
pause "Server running? Press Enter to open the page."
open_url "http://localhost:8000/purchase.html?cb=stripe-test"
printf '\n'
step "Hard-reload the page (Ctrl+Shift+R). The JS changed and this project has"
step "  produced false bug reports twice from a cached module."
step "Click 'Own the Digital Album'. It should leave for Stripe immediately."
step "Pay with card 4242 4242 4242 4242, any future expiry, any CVC, any ZIP."
step "You should land on Stripe's own confirmation message."
printf '\n'
note "Then check the payment arrived:"
open_url "https://dashboard.stripe.com/test/payments"
printf '\n'
step "The \$20.00 payment should be listed, and it should say Succeeded."
printf '\n'
warn "Expected, and not a bug: no email reaches you with the album, no download"
note "  link is issued, and nothing is numbered. Fulfilment under Payment Links"
note "  is entirely manual — you, by hand, per order. STRIPE-SETUP.md section 6."
printf '\n'
confirm "Did the payment go through and show as Succeeded?" \
  && note "Good. The path works end to end." \
  || { warn "Then do not commit the URL yet."
       note "  Check: were you in test mode? Did the button navigate at all?"
       note "  Run with the browser console open — start() logs why it refused."
       SKIPPED+=("the test purchase did not succeed — the URL is written but unproven"); }

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "What is still NOT done"

say "The Digital Edition can take a test payment. Be clear about the rest."
printf '\n'
warn "STILL TRUE AFTER THIS WIZARD:"
note "  - This is TEST mode. No real money can move until you make a live-mode"
note "    product and link and swap the URL. Test and live links are different."
note "  - Nothing delivers the album. No download, no email, no expiring link."
note "    You send it by hand when Stripe tells you someone paid."
note "  - The STANDBY panels on purchase-success.html and purchase-cancelled.html"
note "    still say purchasing is not open. They are correct while the link uses"
note "    Stripe's confirmation page and nobody is routed to those pages. When"
note "    you add the redirect, remove the panels IN THE SAME CHANGE, or they"
note "    become the new lie."
note "  - Deluxe and Artifact stay closed. Artifact is also status:'coming-soon',"
note "    which refuses before it ever looks at a URL."
note "  - No purchase page is deployed. main has none of them."
printf '\n'
say "Before you commit, prove no secret got in:"
note "  grep -rIn \"sk_live\\|sk_test\\|whsec_\" . --exclude=STRIPE-SETUP.md --exclude-dir=.git"
printf '\n'
say "That should return nothing. A Payment Link URL is public and safe to commit;"
say "a key is not, and git keeps it even if you delete it afterwards."
printf '\n'
pause "Press Enter for the summary."

finish
